### ISSUE TITLE
Nested module import not working

### ISSUE THREAD

**Issue by SteveKeller** [R-Studio/PSTools#1]
Hi

There are some problems with nested module import. Some files are missing or not found.

- Convert-UnixTimestamp
- Get-DirectoryStats

I will do a pull request to fix this issue.

Kind Regard
Steve

**Comment by R-Studio** [comment]
Hi Steve

Thanks for your pull request.

Kind Regards
Robin

**Comment by R-Studio** [comment]
Hi Steve

Thanks for your pull request.

Kind Regards
Robin
