### ISSUE TITLE
!! The authors of this projects are taking code from other projects without crediting the original authors !!

### ISSUE THREAD

**Issue by adamency** [R-Studio/PSTools#30]
Just thought people should know when visiting this project. They are taking scripts from others and rebranding them as theirs with an illicit "Copyright ..." notice.

This file for instance `Get-FileLockProcess.ps1` comes from this project: https://github.com/pldmgg/misc-powershell/blob/master/MyFunctions/PowerShellCore_Compatible/Get-FileLockProcess.ps1

Surely there are others.

**Comment by R-Studio** [comment]
Hi @adamency, this was never my intention, but you are right, I saw in the Get-FileLockProcess.ps1, there was the .NOTES part missing. I added this and I also mentioned [pldmgg](https://github.com/pldmgg) the PowerShell script author. _I don't removed the .NOTES, I think as I copy the script maybe this source was already missing .NOTES._

I also removed the license part and added "_Not all functions were written by me._" to clearify that not all functions are written by me.

If you find others, then let me know. It is no problem to add the author.
